/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/alerts/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get operational alert gate status (always disabled for experimental views) */
        get: operations["get_alerts_status_api_v1_alerts_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/artifacts/{artifact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download a generated artifact by ID */
        get: operations["get_artifact_api_v1_artifacts__artifact_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Đăng nhập tài khoản và nhận JWT token */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lấy thông tin tài khoản hiện tại */
        get: operations["get_me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Danh sách tài khoản (Chỉ dành cho Admin) */
        get: operations["list_users_api_v1_auth_users_get"];
        put?: never;
        /** Tạo tài khoản mới (Chỉ dành cho Admin) */
        post: operations["create_user_api_v1_auth_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/users/{user_id}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Thay đổi vai trò tài khoản (Chỉ dành cho Admin) */
        put: operations["update_user_role_api_v1_auth_users__user_id__role_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List registered recorded video assets */
        get: operations["list_media_api_v1_media_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload a video file to the server catalog */
        post: operations["upload_media_api_v1_media_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media/{asset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get media asset metadata */
        get: operations["get_media_asset_api_v1_media__asset_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media/{asset_id}/frame": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Extract single frame as JPEG for zone calibration */
        get: operations["get_media_frame_api_v1_media__asset_id__frame_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media/{asset_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream video with HTTP 206 Range support */
        get: operations["stream_media_api_v1_media__asset_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/model/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get active crowd model profile and applicability status */
        get: operations["get_model_profile_api_v1_model_profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List analysis sessions */
        get: operations["list_sessions_api_v1_sessions_get"];
        put?: never;
        /** Create and start a new analysis session */
        post: operations["create_session_api_v1_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get session state and progress */
        get: operations["get_session_api_v1_sessions__session_id__get"];
        put?: never;
        post?: never;
        /** Purge session, related records, and artifacts */
        delete: operations["delete_session_api_v1_sessions__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request cooperative cancellation of a running session */
        post: operations["cancel_session_api_v1_sessions__session_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/dataset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download complete session observation dataset JSON for smooth frontend playback */
        get: operations["get_session_dataset_api_v1_sessions__session_id__dataset_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream session progress via Server-Sent Events (SSE) */
        get: operations["stream_session_events_api_v1_sessions__session_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export session observation archive or CSV counts */
        get: operations["export_session_api_v1_sessions__session_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/frames": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Query observations within a media time window */
        get: operations["get_frames_in_range_api_v1_sessions__session_id__frames_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/frames/at": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get nearest frame observation at time t with freshness policy applied */
        get: operations["get_frame_at_time_api_v1_sessions__session_id__frames_at_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/heatmap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download session heatmap PNG image */
        get: operations["get_session_heatmap_api_v1_sessions__session_id__heatmap_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/heatmaps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate an image-space relative heat map */
        post: operations["generate_heatmap_api_v1_sessions__session_id__heatmaps_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/heatmaps/{artifact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download heat map image or metadata */
        get: operations["get_heatmap_artifact_api_v1_sessions__session_id__heatmaps__artifact_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List operator notes for session */
        get: operations["list_notes_api_v1_sessions__session_id__notes_get"];
        put?: never;
        /** Create an operator note */
        post: operations["create_note_api_v1_sessions__session_id__notes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/notes/{note_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete an operator note */
        delete: operations["delete_note_api_v1_sessions__session_id__notes__note_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/peaks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get highlight peak visible person moments */
        get: operations["get_peaks_api_v1_sessions__session_id__peaks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get comprehensive session quality summary */
        get: operations["get_quality_summary_api_v1_sessions__session_id__summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/trends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Query visible person time trends for a zone */
        get: operations["get_trends_api_v1_sessions__session_id__trends_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/zone-sets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all zone sets with version history */
        get: operations["list_zone_sets_api_v1_zone_sets_get"];
        put?: never;
        /** Create a new zone set with initial version (v1) */
        post: operations["create_zone_set_api_v1_zone_sets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/zone-sets/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate zone geometries in real time */
        post: operations["validate_zones_api_v1_zone_sets_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/zone-sets/{zone_set_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get zone set by ID */
        get: operations["get_zone_set_api_v1_zone_sets__zone_set_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/zone-sets/{zone_set_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Append a new immutable version */
        post: operations["create_zone_set_version_api_v1_zone_sets__zone_set_id__versions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["liveness_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness probe */
        get: operations["readiness_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AlertStatusResponse */
        AlertStatusResponse: {
            /** Operational Alerts Allowed */
            operational_alerts_allowed: boolean;
            /** Reason */
            reason: string;
            /** Status */
            status: string;
        };
        /** CreateUserRequest */
        CreateUserRequest: {
            /** Email */
            email: string;
            /**
             * Full Name
             * @default
             */
            full_name: string;
            /** Password */
            password: string;
            /**
             * Role
             * @description ADMIN, OPERATOR, hoặc VIEWER
             * @default OPERATOR
             */
            role: string;
            /** Username */
            username: string;
        };
        /** FrameDataResponse */
        FrameDataResponse: {
            /** Frame Index */
            frame_index: number;
            /** Freshness */
            freshness: string;
            /** Media Time S */
            media_time_s: number;
            /** Observation */
            observation: {
                [key: string]: unknown;
            };
            /** Quality */
            quality: string;
            /** Session Id */
            session_id: string;
            /** Zones */
            zones: components["schemas"]["ZoneResultResponse"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HeatmapGenerateRequest */
        HeatmapGenerateRequest: {
            /**
             * Normalization Method
             * @default SESSION_MAX
             * @enum {string}
             */
            normalization_method: "SESSION_MAX" | "WINDOW_MAX";
            /** Window From T */
            window_from_t?: number | null;
            /** Window To T */
            window_to_t?: number | null;
        };
        /** HeatmapMetadataModel */
        HeatmapMetadataModel: {
            /** Artifact Id */
            artifact_id: string;
            /** Colormap */
            colormap: string;
            /** Disclaimer */
            disclaimer: string;
            /** Frames Discarded */
            frames_discarded: number;
            /** Frames Used */
            frames_used: number;
            /** Image Height */
            image_height: number;
            /** Image Width */
            image_width: number;
            /**
             * Kind
             * @default IMAGE_SPACE
             */
            kind: string;
            /** Normalization Method */
            normalization_method: string;
            /** Sha256 */
            sha256: string;
            /** Window From T */
            window_from_t: number | null;
            /** Window To T */
            window_to_t: number | null;
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Password
             * @description Mật khẩu
             */
            password: string;
            /**
             * Username
             * @description Tên đăng nhập
             */
            username: string;
        };
        /** LoginResponse */
        LoginResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            user: components["schemas"]["UserProfileResponse"];
        };
        /** MediaAssetResponse */
        MediaAssetResponse: {
            /** Browser Playable */
            browser_playable: boolean;
            /** Codec */
            codec: string;
            /** Display Code */
            display_code?: string | null;
            /** Display Name */
            display_name: string;
            /** Duration S */
            duration_s: number;
            /** Fps */
            fps: number;
            /** Frame Count */
            frame_count: number;
            /** Height */
            height: number;
            /** Id */
            id: string;
            /** Sha256 */
            sha256: string;
            /** Width */
            width: number;
        };
        /** ModelProfileResponse */
        ModelProfileResponse: {
            /** Applicability Status */
            applicability_status: string;
            /** Checkpoint Available */
            checkpoint_available: boolean;
            /** Checkpoint Env */
            checkpoint_env: string;
            /** Checkpoint Sha256 */
            checkpoint_sha256: string;
            /**
             * Confidence Semantics
             * @description Uncalibrated model score, not a probability.
             * @default RAW_MODEL_SCORE
             */
            confidence_semantics: string;
            /** Experimental Warning */
            experimental_warning: string;
            /** Image Size */
            image_size: number;
            /** Model Family */
            model_family: string;
            /** Operational Alerts Allowed */
            operational_alerts_allowed: boolean;
            /** Profile Id */
            profile_id: string;
            /** Raw Confidence Threshold */
            raw_confidence_threshold: number;
        };
        /** NoteCreateModel */
        NoteCreateModel: {
            /**
             * Author
             * @default operator
             */
            author: string;
            /** Media Time S */
            media_time_s: number;
            /** Text */
            text: string;
            /** Zone Id */
            zone_id?: string | null;
        };
        /** NoteResponseModel */
        NoteResponseModel: {
            /** Author */
            author: string;
            /** Created At */
            created_at: string;
            /** Id */
            id: string;
            /** Media Time S */
            media_time_s: number;
            /** Session Id */
            session_id: string;
            /** Text */
            text: string;
            /** Zone Id */
            zone_id: string | null;
        };
        /** PeakMomentModel */
        PeakMomentModel: {
            /** Description */
            description: string;
            /** Description Vi */
            description_vi: string;
            /** Frame Index */
            frame_index: number;
            /** Media Time S */
            media_time_s: number;
            /** Visible Count */
            visible_count: number;
            /** Zone Id */
            zone_id: string;
        };
        /** PeaksResponse */
        PeaksResponse: {
            /** Experimental Warning */
            experimental_warning: string;
            /** Peaks */
            peaks: components["schemas"]["PeakMomentModel"][];
            /** Session Id */
            session_id: string;
            /** Zone Id */
            zone_id: string;
        };
        /** RawPointModel */
        RawPointModel: {
            /** Availability */
            availability: string;
            /** Media Time S */
            media_time_s: number;
            /** Visible Count */
            visible_count?: number | null;
        };
        /**
         * SeriesMode
         * @enum {string}
         */
        SeriesMode: "RAW" | "BUCKETED" | "SMOOTHED";
        /** SessionCreateRequest */
        SessionCreateRequest: {
            /** Media Asset Id */
            media_asset_id: string;
            /** Options */
            options?: {
                [key: string]: unknown;
            };
            /** Synthetic */
            synthetic?: boolean | null;
            /**
             * Use Synthetic
             * @default false
             */
            use_synthetic: boolean;
            /** Zone Set Version Id */
            zone_set_version_id: string;
        };
        /** SessionResponse */
        SessionResponse: {
            /** Checkpoint Sha256 */
            checkpoint_sha256: string;
            /** Completeness */
            completeness: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Display Code */
            display_code?: string | null;
            /** Duration S */
            duration_s?: number | null;
            /** Error Code */
            error_code: string | null;
            /** Id */
            id: string;
            /** Media Asset Id */
            media_asset_id: string;
            /** Media Name */
            media_name?: string | null;
            /** Model Profile Id */
            model_profile_id: string;
            /** Model Profile Sha256 */
            model_profile_sha256: string;
            /** Options */
            options: {
                [key: string]: unknown;
            };
            /** Processed Frames */
            processed_frames: number;
            /** Progress */
            progress: number;
            /** Status */
            status: string;
            /** Synthetic */
            synthetic: boolean;
            /** Total Frames */
            total_frames: number;
            /** Tracker Config Sha256 */
            tracker_config_sha256: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** User Action Hint */
            user_action_hint: string | null;
            /** Video Src */
            video_src?: string | null;
            /** Zone Set Name */
            zone_set_name?: string | null;
            /** Zone Set Version Id */
            zone_set_version_id: string;
        };
        /** SmoothedPointModel */
        SmoothedPointModel: {
            /**
             * Is Derived
             * @default true
             */
            is_derived: boolean;
            /** Media Time S */
            media_time_s: number;
            /** Smoothed Value */
            smoothed_value?: number | null;
        };
        /** TrendBucketModel */
        TrendBucketModel: {
            /** Availability Ratio */
            availability_ratio: number;
            /** Bucket Index */
            bucket_index: number;
            /** From T */
            from_t: number;
            /** Max */
            max?: number | null;
            /** Mean */
            mean?: number | null;
            /** Median */
            median?: number | null;
            /** Min */
            min?: number | null;
            /** N Counted */
            n_counted: number;
            /** N Frames */
            n_frames: number;
            /** P95 */
            p95?: number | null;
            /** To T */
            to_t: number;
        };
        /** TrendsResponse */
        TrendsResponse: {
            /** Bucket S */
            bucket_s?: number | null;
            /** Buckets */
            buckets?: components["schemas"]["TrendBucketModel"][] | null;
            /** Experimental Warning */
            experimental_warning: string;
            /** Raw Points */
            raw_points?: components["schemas"]["RawPointModel"][] | null;
            series_mode: components["schemas"]["SeriesMode"];
            /** Session Id */
            session_id: string;
            /** Smoothed Points */
            smoothed_points?: components["schemas"]["SmoothedPointModel"][] | null;
            /** Zone Id */
            zone_id: string;
        };
        /** UpdateRoleRequest */
        UpdateRoleRequest: {
            /**
             * Role
             * @description ADMIN, OPERATOR, hoặc VIEWER
             */
            role: string;
        };
        /** UserProfileResponse */
        UserProfileResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Email */
            email: string;
            /** Full Name */
            full_name: string;
            /** Id */
            id: string;
            /** Is Active */
            is_active: boolean;
            /** Role */
            role: string;
            /** Username */
            username: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** ValidationRequest */
        ValidationRequest: {
            /** Image Height */
            image_height: number;
            /** Image Width */
            image_width: number;
            /** Zones */
            zones: components["schemas"]["ZoneInput"][];
        };
        /** ValidationResponse */
        ValidationResponse: {
            /** Errors */
            errors: string[];
            /** Is Valid */
            is_valid: boolean;
            /** Warnings */
            warnings: string[];
        };
        /** ZoneInput */
        ZoneInput: {
            /** Blind Regions */
            blind_regions?: number[][][];
            /** Description */
            description?: string | null;
            /** Name */
            name: string;
            /** Vertices */
            vertices: number[][];
            /** Zone Id */
            zone_id: string;
        };
        /** ZoneResultResponse */
        ZoneResultResponse: {
            /** Availability */
            availability: string;
            /** Density People Per M2 */
            density_people_per_m2?: number | null;
            /**
             * Density Status
             * @default UNAVAILABLE_NO_CALIBRATION
             */
            density_status: string;
            /** Visible Count */
            visible_count: number | null;
            /** Zone Id */
            zone_id: string;
        };
        /** ZoneSetCreateRequest */
        ZoneSetCreateRequest: {
            /** Id */
            id: string;
            /** Image Height */
            image_height: number;
            /** Image Width */
            image_width: number;
            /** Name */
            name: string;
            /** Zones */
            zones: components["schemas"]["ZoneInput"][];
        };
        /** ZoneSetDetailResponse */
        ZoneSetDetailResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Versions */
            versions: components["schemas"]["ZoneSetVersionResponse"][];
        };
        /** ZoneSetVersionResponse */
        ZoneSetVersionResponse: {
            /** Id */
            id: string;
            /** Image Height */
            image_height: number;
            /** Image Width */
            image_width: number;
            /** Polygon Data */
            polygon_data: {
                [key: string]: unknown;
            };
            /** Sha256 */
            sha256: string;
            /** Version */
            version: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_alerts_status_api_v1_alerts_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertStatusResponse"];
                };
            };
        };
    };
    get_artifact_api_v1_artifacts__artifact_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_api_v1_auth_users_get: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_user_api_v1_auth_users_post: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_role_api_v1_auth_users__user_id__role_put: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
            };
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRoleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_media_api_v1_media_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaAssetResponse"][];
                };
            };
        };
    };
    upload_media_api_v1_media_upload_post: {
        parameters: {
            query: {
                /** @description Tên tệp video tải lên */
                filename: string;
                /** @description Tên hiển thị trong danh mục */
                display_name?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaAssetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_media_asset_api_v1_media__asset_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaAssetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_media_frame_api_v1_media__asset_id__frame_get: {
        parameters: {
            query?: {
                frame_index?: number;
            };
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_media_api_v1_media__asset_id__stream_get: {
        parameters: {
            query?: never;
            header?: {
                Range?: string | null;
            };
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_model_profile_api_v1_model_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelProfileResponse"];
                };
            };
        };
    };
    list_sessions_api_v1_sessions_get: {
        parameters: {
            query?: {
                status?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_session_api_v1_sessions_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_api_v1_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_session_api_v1_sessions__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_session_api_v1_sessions__session_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_dataset_api_v1_sessions__session_id__dataset_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_session_events_api_v1_sessions__session_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_session_api_v1_sessions__session_id__export_get: {
        parameters: {
            query?: {
                /** @description Export format */
                format?: "jsonl" | "csv";
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_frames_in_range_api_v1_sessions__session_id__frames_get: {
        parameters: {
            query?: {
                from_t?: number;
                to_t?: number;
                limit?: number;
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_frame_at_time_api_v1_sessions__session_id__frames_at_get: {
        parameters: {
            query: {
                /** @description Playback media_time_s */
                t: number;
                max_gap_s?: number;
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrameDataResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_heatmap_api_v1_sessions__session_id__heatmap_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_heatmap_api_v1_sessions__session_id__heatmaps_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HeatmapGenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HeatmapMetadataModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_heatmap_artifact_api_v1_sessions__session_id__heatmaps__artifact_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_notes_api_v1_sessions__session_id__notes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteResponseModel"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_note_api_v1_sessions__session_id__notes_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoteCreateModel"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteResponseModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_note_api_v1_sessions__session_id__notes__note_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                note_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_peaks_api_v1_sessions__session_id__peaks_get: {
        parameters: {
            query: {
                /** @description Target zone ID */
                zone_id: string;
                /** @description Max highlights */
                limit?: number;
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PeaksResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_quality_summary_api_v1_sessions__session_id__summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trends_api_v1_sessions__session_id__trends_get: {
        parameters: {
            query: {
                /** @description Target zone ID */
                zone_id: string;
                /** @description Bucket duration in seconds */
                bucket_s?: number;
                /** @description Series presentation mode */
                series?: components["schemas"]["SeriesMode"];
                /** @description Max downsample points */
                max_points?: number;
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrendsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_zone_sets_api_v1_zone_sets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ZoneSetDetailResponse"][];
                };
            };
        };
    };
    create_zone_set_api_v1_zone_sets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ZoneSetCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ZoneSetDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_zones_api_v1_zone_sets_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValidationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_zone_set_api_v1_zone_sets__zone_set_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                zone_set_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ZoneSetDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_zone_set_version_api_v1_zone_sets__zone_set_id__versions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                zone_set_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValidationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ZoneSetVersionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    liveness_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    readiness_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
